# Generated by Django 5.2.1 on 2025-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(max_length=150, verbose_name='Phone')),
            ],
        ),
    ]
