# Generated by Django 5.2.3 on 2025-07-25 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'permissions': [('can_publish_product', 'Can publish product'), ('can_unpublish_product', 'Can unpublish product'), ('can_delete_product', 'Can delete product')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
